source("/home/susan/Dropbox/Susan/code/tools.R")
library(ggplot2)

vpower = function(M, n, betavec, lambda, type){
  vec=numeric()
  for(i in 1:M){
    vec[i]= mean(genpower(n,betavec,lambda,type)[,2]) #mean of y's from dataset generated by genpower
  }
  return(vec)
}

type="pl"
n=2000
M=100
betavec=c(0,1)

datf = rbind(data.frame(prop=vpower(M,n,betavec,1/5,type),Lambda=rep("1/5",M)),
             data.frame(prop=vpower(M,n,betavec,1/3,type),Lambda=rep("1/3",M)),
             data.frame(prop=vpower(M,n,betavec,1,type),Lambda=rep("1",M)),
             data.frame(prop=vpower(M,n,betavec,2,type),Lambda=rep("2",M)),
             data.frame(prop=vpower(M,n,betavec,3,type),Lambda=rep("3",M)))
            
  
)
dat1 = data.frame(prop=vpower(M,n,betavec,1/5,type),Lambda=rep("1/5",M))
dat2 = data.frame(prop=vpower(M,n,betavec,1/3,type),Lambda=rep("1/3",M))
dat3 = data.frame(prop=vpower(M,n,betavec,1,type),Lambda=rep("1",M))
dat4 = data.frame(prop=vpower(M,n,betavec,2,type),Lambda=rep("2",M))
dat5 = data.frame(prop=vpower(M,n,betavec,3,type),Lambda=rep("3",M))
datf =rbind(dat1,dat2,dat3,dat4,dat5)

hist = ggplot(datf, aes(x = prop, fill = Lambda)) + geom_histogram(col = "black", bins = 80) +
  scale_fill_grey() + labs(x = "Proporção", y = "Frequência", fill = expression(lambda)) +
  theme_light() + coord_cartesian(xlim = c(0,1), ylim = c(0,50)) + geom_hline(yintercept = 0) +
  theme(axis.title.y = element_text( margin = unit(c(0, 3, 0, 0), "mm")),
        axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm")),
        legend.text = element_text(size = 16), axis.title = element_text(size = 16),
        legend.title = element_text(size=16), plot.title = element_text(size = 18), 
        axis.text = element_text(size = 12))

#gris: scale_fill_brewer(palette = "Set1")

box = ggplot(datf, aes(x=Lambda, y=prop, fill=Lambda)) + geom_boxplot() + 
  labs(y="Proporção", x = expression(lambda)) + scale_fill_grey() + 
  theme_light() + coord_cartesian(ylim = c(0,1)) +
  theme(axis.title.y = element_text( margin = unit(c(0, 3, 0, 0), "mm")),
        axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm")),
        legend.text = element_text(size = 16), axis.title = element_text(size = 16),
        legend.title = element_text(size=16), plot.title = element_text(size = 18), 
        axis.text = element_text(size = 12)) + theme(legend.position="none")

  
  
  
  
  